/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as MainRouteImport } from './routes/_main/route'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminProductsImport } from './routes/admin/products'
import { Route as AdminProductCategoriesImport } from './routes/admin/product-categories'
import { Route as AdminDoctorsImport } from './routes/admin/doctors'
import { Route as AdminBlogsImport } from './routes/admin/blogs'
import { Route as MainServicesImport } from './routes/_main/services'
import { Route as MainProductsImport } from './routes/_main/products'
import { Route as MainLoginImport } from './routes/_main/login'
import { Route as MainContactImport } from './routes/_main/contact'
import { Route as MainAboutImport } from './routes/_main/about'
import { Route as AdminUsersNewImport } from './routes/admin/users_.new'
import { Route as AdminUsersIdImport } from './routes/admin/users_.$id'
import { Route as AdminProductsNewImport } from './routes/admin/products_.new'
import { Route as AdminProductCategoriesNewImport } from './routes/admin/product-categories_.new'
import { Route as AdminDoctorsNewImport } from './routes/admin/doctors_.new'
import { Route as AdminBlogsNewImport } from './routes/admin/blogs_.new'
import { Route as AdminProductCategoriesIdEditImport } from './routes/admin/product-categories_.$id.edit'

// Create/Update Routes

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const MainRouteRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductsRoute = AdminProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductCategoriesRoute = AdminProductCategoriesImport.update({
  id: '/product-categories',
  path: '/product-categories',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminDoctorsRoute = AdminDoctorsImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminBlogsRoute = AdminBlogsImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRouteRoute,
} as any)

const MainServicesRoute = MainServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainProductsRoute = MainProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainLoginRoute = MainLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainContactRoute = MainContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainAboutRoute = MainAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)

const AdminUsersNewRoute = AdminUsersNewImport.update({
  id: '/users_/new',
  path: '/users/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminUsersIdRoute = AdminUsersIdImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductsNewRoute = AdminProductsNewImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductCategoriesNewRoute = AdminProductCategoriesNewImport.update({
  id: '/product-categories_/new',
  path: '/product-categories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminDoctorsNewRoute = AdminDoctorsNewImport.update({
  id: '/doctors_/new',
  path: '/doctors/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminBlogsNewRoute = AdminBlogsNewImport.update({
  id: '/blogs_/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProductCategoriesIdEditRoute =
  AdminProductCategoriesIdEditImport.update({
    id: '/product-categories_/$id/edit',
    path: '/product-categories/$id/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/products': {
      id: '/_main/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof MainProductsImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/services': {
      id: '/_main/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MainServicesImport
      parentRoute: typeof MainRouteImport
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/product-categories': {
      id: '/admin/product-categories'
      path: '/product-categories'
      fullPath: '/admin/product-categories'
      preLoaderRoute: typeof AdminProductCategoriesImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/blogs_/new': {
      id: '/admin/blogs_/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/doctors_/new': {
      id: '/admin/doctors_/new'
      path: '/doctors/new'
      fullPath: '/admin/doctors/new'
      preLoaderRoute: typeof AdminDoctorsNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/product-categories_/new': {
      id: '/admin/product-categories_/new'
      path: '/product-categories/new'
      fullPath: '/admin/product-categories/new'
      preLoaderRoute: typeof AdminProductCategoriesNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/products_/new': {
      id: '/admin/products_/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users_/$id': {
      id: '/admin/users_/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users_/new': {
      id: '/admin/users_/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/product-categories_/$id/edit': {
      id: '/admin/product-categories_/$id/edit'
      path: '/product-categories/$id/edit'
      fullPath: '/admin/product-categories/$id/edit'
      preLoaderRoute: typeof AdminProductCategoriesIdEditImport
      parentRoute: typeof AdminRouteImport
    }
  }
}

// Create and export the route tree

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainContactRoute: typeof MainContactRoute
  MainLoginRoute: typeof MainLoginRoute
  MainProductsRoute: typeof MainProductsRoute
  MainServicesRoute: typeof MainServicesRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainContactRoute: MainContactRoute,
  MainLoginRoute: MainLoginRoute,
  MainProductsRoute: MainProductsRoute,
  MainServicesRoute: MainServicesRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminProductCategoriesRoute: typeof AdminProductCategoriesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminDoctorsNewRoute: typeof AdminDoctorsNewRoute
  AdminProductCategoriesNewRoute: typeof AdminProductCategoriesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminProductCategoriesIdEditRoute: typeof AdminProductCategoriesIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminProductCategoriesRoute: AdminProductCategoriesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminDoctorsNewRoute: AdminDoctorsNewRoute,
  AdminProductCategoriesNewRoute: AdminProductCategoriesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminProductCategoriesIdEditRoute: AdminProductCategoriesIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/login': typeof MainLoginRoute
  '/products': typeof MainProductsRoute
  '/services': typeof MainServicesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/doctors/new': typeof AdminDoctorsNewRoute
  '/admin/product-categories/new': typeof AdminProductCategoriesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/product-categories/$id/edit': typeof AdminProductCategoriesIdEditRoute
}

export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/login': typeof MainLoginRoute
  '/products': typeof MainProductsRoute
  '/services': typeof MainServicesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/doctors/new': typeof AdminDoctorsNewRoute
  '/admin/product-categories/new': typeof AdminProductCategoriesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/product-categories/$id/edit': typeof AdminProductCategoriesIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/products': typeof MainProductsRoute
  '/_main/services': typeof MainServicesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blogs_/new': typeof AdminBlogsNewRoute
  '/admin/doctors_/new': typeof AdminDoctorsNewRoute
  '/admin/product-categories_/new': typeof AdminProductCategoriesNewRoute
  '/admin/products_/new': typeof AdminProductsNewRoute
  '/admin/users_/$id': typeof AdminUsersIdRoute
  '/admin/users_/new': typeof AdminUsersNewRoute
  '/admin/product-categories_/$id/edit': typeof AdminProductCategoriesIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/about'
    | '/contact'
    | '/login'
    | '/products'
    | '/services'
    | '/admin/blogs'
    | '/admin/doctors'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/users'
    | '/'
    | '/admin/'
    | '/admin/blogs/new'
    | '/admin/doctors/new'
    | '/admin/product-categories/new'
    | '/admin/products/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/product-categories/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/login'
    | '/products'
    | '/services'
    | '/admin/blogs'
    | '/admin/doctors'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/admin/blogs/new'
    | '/admin/doctors/new'
    | '/admin/product-categories/new'
    | '/admin/products/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/product-categories/$id/edit'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/_main/about'
    | '/_main/contact'
    | '/_main/login'
    | '/_main/products'
    | '/_main/services'
    | '/admin/blogs'
    | '/admin/doctors'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/users'
    | '/_main/'
    | '/admin/'
    | '/admin/blogs_/new'
    | '/admin/doctors_/new'
    | '/admin/product-categories_/new'
    | '/admin/products_/new'
    | '/admin/users_/$id'
    | '/admin/users_/new'
    | '/admin/product-categories_/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main",
        "/admin"
      ]
    },
    "/_main": {
      "filePath": "_main/route.tsx",
      "children": [
        "/_main/about",
        "/_main/contact",
        "/_main/login",
        "/_main/products",
        "/_main/services",
        "/_main/"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/blogs",
        "/admin/doctors",
        "/admin/product-categories",
        "/admin/products",
        "/admin/users",
        "/admin/",
        "/admin/blogs_/new",
        "/admin/doctors_/new",
        "/admin/product-categories_/new",
        "/admin/products_/new",
        "/admin/users_/$id",
        "/admin/users_/new",
        "/admin/product-categories_/$id/edit"
      ]
    },
    "/_main/about": {
      "filePath": "_main/about.tsx",
      "parent": "/_main"
    },
    "/_main/contact": {
      "filePath": "_main/contact.tsx",
      "parent": "/_main"
    },
    "/_main/login": {
      "filePath": "_main/login.tsx",
      "parent": "/_main"
    },
    "/_main/products": {
      "filePath": "_main/products.tsx",
      "parent": "/_main"
    },
    "/_main/services": {
      "filePath": "_main/services.tsx",
      "parent": "/_main"
    },
    "/admin/blogs": {
      "filePath": "admin/blogs.tsx",
      "parent": "/admin"
    },
    "/admin/doctors": {
      "filePath": "admin/doctors.tsx",
      "parent": "/admin"
    },
    "/admin/product-categories": {
      "filePath": "admin/product-categories.tsx",
      "parent": "/admin"
    },
    "/admin/products": {
      "filePath": "admin/products.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/blogs_/new": {
      "filePath": "admin/blogs_.new.tsx",
      "parent": "/admin"
    },
    "/admin/doctors_/new": {
      "filePath": "admin/doctors_.new.tsx",
      "parent": "/admin"
    },
    "/admin/product-categories_/new": {
      "filePath": "admin/product-categories_.new.tsx",
      "parent": "/admin"
    },
    "/admin/products_/new": {
      "filePath": "admin/products_.new.tsx",
      "parent": "/admin"
    },
    "/admin/users_/$id": {
      "filePath": "admin/users_.$id.tsx",
      "parent": "/admin"
    },
    "/admin/users_/new": {
      "filePath": "admin/users_.new.tsx",
      "parent": "/admin"
    },
    "/admin/product-categories_/$id/edit": {
      "filePath": "admin/product-categories_.$id.edit.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
